[[pages]]
path = "main.py"
name = "é¦–é¡µ"
icon = "ğŸ "

[[pages]]
path = "pages/hots.py"
name = "çƒ­ç‚¹åº“"
icon = "ğŸ”¥"
url_path = "hots"

[[pages]]
path = "pages/accounts.py"
name = "è´¦å·ç®¡ç†"
icon = "ğŸ‘¥"
url_path = "accounts"

[[pages]]
path = "pages/tasks.py"
name = "ä»»åŠ¡ä¸­å¿ƒ"
icon = "ğŸ§¾"
url_path = "tasks"

[[pages]]
path = "pages/my.py"
name = "ä¸ªäººä¸­å¿ƒ"
icon = "ğŸ‘¨â€ğŸ’¼"
url_path = "my"


[[pages]]
path = "pages/auto.py"
name = "AIæ‰˜ç®¡"
icon = "ğŸ¤–"
url_path = "auto"


[[pages]]
path = "pages/exit.py"
name = "é€€å‡ºç™»å½•"
icon = "âŒ"
url_path = "exit"
